import { supabase } from './supabase'

export const SEED_SETTINGS = [
  { key: 'countdown_target', value: '2025-06-18T16:00:00+05:30' },
  { key: 'hero_subtitle', value: 'June 18 - 19  ·  5 people' },
  { key: 'weather_text', value: 'Hyderabad on June 18  ·  38°C, Hot & Humid' },
  { key: 'weather_sub', value: 'Carry a refillable water bottle and ORS packets.' },
]

export const SEED_STOPS = [
  {
    id: 'stop-1',
    day: 1,
    sort_order: 1,
    time: '4:00 PM',
    date: '2025-06-18',
    name: 'Kacheguda Railway Station',
    location: 'Arrival point',
    distance: '—',
    entry_fee: 0,
    duration: '45 min',
    description: 'Arrival. Check into hotel in the Somajiguda / Necklace Road area. "Somajiguda area. Central to everything. Do not cheap out on location." — Abhay. Alt: FabHotel Necklace Road (Rs. 999–1,500/night) or Hotel Geetanjali (Rs. 1,200–1,800/night). Book 2 rooms, split between 4 people.',
    photo_spot: null,
    abhay_note: 'Somajiguda area. Central to everything. Do not cheap out on location.',
    alternative_name: 'FabHotel Necklace Road or Hotel Geetanjali',
    alternative_maps_url: 'https://maps.google.com/?q=FabHotel+Necklace+Road+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Kacheguda+Railway+Station',
  },
  {
    id: 'stop-2',
    day: 1,
    sort_order: 2,
    time: '5:00 PM',
    date: '2025-06-18',
    name: 'Nimrah Cafe & Bakery',
    location: 'Old City',
    distance: '6 km from station ~20 min Uber Rs. 120',
    entry_fee: 0,
    duration: '20 min',
    description: 'The most iconic Irani chai stop in Hyderabad. Standing room only. Cash only. "Cash only. Don’t argue about it. Carry Rs. 100 notes." — Abhay',
    photo_spot: 'Charminar framed across the road while drinking chai',
    abhay_note: 'Cash only. Don\'t argue about it. Carry Rs. 100 notes.',
    alternative_name: 'Cafe Niloufer, Himayat Nagar',
    alternative_maps_url: 'https://maps.google.com/?q=Cafe+Niloufer+Himayat+Nagar',
    directions_url: 'https://maps.google.com/?q=Nimrah+Cafe+Hyderabad',
  },
  {
    id: 'stop-3',
    day: 1,
    sort_order: 3,
    time: '5:20 PM',
    date: '2025-06-18',
    name: 'Charminar + Laad Bazaar',
    location: 'Old City',
    distance: '2 min walk from Nimrah',
    entry_fee: 25,
    duration: '60–70 min',
    description: 'Climb inside for the rooftop view over the bazaars. Walk Laad Bazaar (bangles, pearls, attar). Visit Mecca Masjid next door. "Climb inside. The stairs are narrow. Alwin will complain. Go anyway." — Abhay',
    photo_spot: 'Rooftop view of bazaars at dusk from inside Charminar',
    abhay_note: 'Climb inside. The stairs are narrow. Alwin will complain. Go anyway.',
    alternative_name: 'Walk the exterior and bazaar for free if Charminar is closed at arrival time',
    alternative_maps_url: 'https://maps.google.com/?q=Charminar+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Charminar+Hyderabad',
  },
  {
    id: 'stop-4',
    day: 1,
    sort_order: 4,
    time: '7:00 PM',
    date: '2025-06-18',
    name: 'Dinner — Cafe Shadab',
    location: 'Old City',
    distance: '5 min walk from Charminar',
    entry_fee: 0,
    duration: '60 min',
    description: 'One of Hyderabad’s oldest and most respected restaurants. Sit down, order heavy. "Order haleem even if you think you’re full. You’re never full." — Abhay',
    photo_spot: null,
    abhay_note: 'Order haleem even if you think you\'re full. You\'re never full.',
    alternative_name: 'Shah Ghouse, Tolichowki — 8 km away, arguably better biryani, but farther.',
    alternative_maps_url: 'https://maps.google.com/?q=Shah+Ghouse+Tolichowki',
    directions_url: 'https://maps.google.com/?q=Cafe+Shadab+Hyderabad',
  },
  {
    id: 'stop-5',
    day: 1,
    sort_order: 5,
    time: '8:30 PM',
    date: '2025-06-18',
    name: 'Hussain Sagar Lake + Lumbini Park',
    location: 'Necklace Road',
    distance: '10 km from Shadab ~20 min Uber Rs. 150',
    entry_fee: 170,
    duration: '90 min',
    description: 'Ferry ride to the Buddha statue in the middle of the lake. Laser show runs at 8:30 PM — be at the gate by 8:15 PM. "Laser show at 8:30 PM. Gate by 8:15. Do not miss it." — Abhay',
    photo_spot: 'Buddha statue from the ferry at dusk. Necklace Road lit up at night.',
    abhay_note: 'Laser show at 8:30 PM. Gate by 8:15. Do not miss it.',
    alternative_name: 'Just walk Necklace Road (free, still beautiful). Skip the laser show if tired.',
    alternative_maps_url: 'https://maps.google.com/?q=Necklace+Road+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Lumbini+Park+Hyderabad',
  },
  {
    id: 'stop-6',
    day: 1,
    sort_order: 6,
    time: '10:00 PM',
    date: '2025-06-18',
    name: 'Eat Street, Necklace Road',
    location: 'Necklace Road',
    distance: '2 min walk from Lumbini Park',
    entry_fee: 0,
    duration: '60 min',
    description: 'Late-night street food strip overlooking Hussain Sagar. Good vibe to close Day 1. "Last stop of the night. Don’t overeat. Two days of biryani ahead." — Abhay',
    photo_spot: 'Lakeside lights from Eat Street at night.',
    abhay_note: 'Last stop of the night. Don\'t overeat. Two days of biryani ahead.',
    alternative_name: 'Any rooftop cafe on Banjara Hills for a quieter close.',
    alternative_maps_url: 'https://maps.google.com/?q=Banjara+Hills+rooftop+cafes',
    directions_url: 'https://maps.google.com/?q=Eat+Street+Necklace+Road+Hyderabad',
  },
  {
    id: 'stop-7',
    day: 2,
    sort_order: 7,
    time: '10:00 AM',
    date: '2025-06-19',
    name: 'Chowmahalla Palace',
    location: 'Old City',
    distance: '6 km from hotel ~15 min Uber Rs. 100',
    entry_fee: 80,
    duration: '90 min',
    description: 'Former seat of the Nizam of Hyderabad. Durbar Hall with Belgian chandeliers, Nizam’s vintage European car collection, royal courtyards. "Don’t rush this one. The Durbar Hall chandeliers are extraordinary." — Abhay',
    photo_spot: 'Durbar Hall chandeliers from below. Vintage cars courtyard.',
    abhay_note: 'Don\'t rush this one. The Durbar Hall chandeliers are extraordinary.',
    alternative_name: 'Qutb Shahi Tombs — Rs. 15/person, 3 km away. OR Birla Mandir — free, hilltop temple with views.',
    alternative_maps_url: 'https://maps.google.com/?q=Qutb+Shahi+Tombs+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Chowmahalla+Palace+Hyderabad',
  },
  {
    id: 'stop-8',
    day: 2,
    sort_order: 8,
    time: '12:00 PM',
    date: '2025-06-19',
    name: 'Lunch — Bawarchi',
    location: 'RTC Cross Road',
    distance: '5 km from Chowmahalla ~15 min Uber Rs. 90',
    entry_fee: 0,
    duration: '60 min',
    description: 'The original Bawarchi on RTC Cross Road. No branches. Perfectly cooked biryani since 1978. "This is the original. No branches. Anyone who says otherwise is wrong." — Abhay',
    photo_spot: null,
    abhay_note: 'This is the original. No branches. Anyone who says otherwise is wrong.',
    alternative_name: 'Cafe Bahar, Basheerbagh — 3 km, equally legendary for haleem and butter chicken.',
    alternative_maps_url: 'https://maps.google.com/?q=Cafe+Bahar+Basheerbagh',
    directions_url: 'https://maps.google.com/?q=Bawarchi+RTC+Cross+Road+Hyderabad',
  },
  {
    id: 'stop-9',
    day: 2,
    sort_order: 9,
    time: '2:00 PM',
    date: '2025-06-19',
    name: 'KBR National Park',
    location: 'Jubilee Hills',
    distance: '8 km from Bawarchi ~20 min Uber Rs. 130',
    entry_fee: 0,
    duration: '60 min',
    description: 'A forest reserve inside the city. 2.4 km walking trail under full canopy. Good recovery from biryani. "Post-lunch walk through a forest inside the city. Sounds boring. It isn’t." — Abhay',
    photo_spot: 'Canopy trail — dense, green, unexpectedly cinematic.',
    abhay_note: 'Post-lunch walk through a forest inside the city. Sounds boring. It isn\'t.',
    alternative_name: 'Durgam Cheruvu (Secret Lake, Hitech City) — free, beautiful rock formations, great for photos.',
    alternative_maps_url: 'https://maps.google.com/?q=Durgam+Cheruvu+Hyderabad',
    directions_url: 'https://maps.google.com/?q=KBR+National+Park+Hyderabad',
  },
  {
    id: 'stop-10',
    day: 2,
    sort_order: 10,
    time: '4:00 PM',
    date: '2025-06-19',
    name: 'Snack — Chutneys, Banjara Hills',
    location: 'Banjara Hills',
    distance: '3 km from KBR ~10 min Uber Rs. 80',
    entry_fee: 0,
    duration: '45 min',
    description: 'South Indian snack break. Best pesarattu and filter coffee in the area. "Pesarattu and filter coffee. This is mandatory." — Abhay',
    photo_spot: null,
    abhay_note: 'Pesarattu and filter coffee. This is mandatory.',
    alternative_name: 'Any cafe in Jubilee Hills or Banjara Hills for coffee and snacks.',
    alternative_maps_url: 'https://maps.google.com/?q=cafes+Jubilee+Hills+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Chutneys+Banjara+Hills+Hyderabad',
  },
  {
    id: 'stop-11',
    day: 2,
    sort_order: 11,
    time: '5:30 PM',
    date: '2025-06-19',
    name: 'Dinner — Paradise Biryani, Secunderabad',
    location: 'Secunderabad',
    distance: '8 km from Banjara Hills ~20 min Uber Rs. 130',
    entry_fee: 0,
    duration: '90 min',
    description: 'The original Paradise, open since 1953. The final meal of the trip. Order heavy. No regrets. "Last meal. Since 1953. Go hard." — Abhay',
    photo_spot: null,
    abhay_note: 'Last meal. Since 1953. Go hard.',
    alternative_name: 'Pista House (haleem, 5 km from Secunderabad station) OR Hotel Shadab Secunderabad branch.',
    alternative_maps_url: 'https://maps.google.com/?q=Pista+House+Hyderabad',
    directions_url: 'https://maps.google.com/?q=Paradise+Biryani+Secunderabad',
  },
  {
    id: 'stop-12',
    day: 2,
    sort_order: 12,
    time: '8:30 PM',
    date: '2025-06-19',
    name: 'Secunderabad Railway Station',
    location: 'Secunderabad',
    distance: '2 km from Paradise ~5 min Uber Rs. 60',
    entry_fee: 0,
    duration: null,
    description: 'Departure. Board the train. Trip complete.',
    photo_spot: null,
    abhay_note: null,
    alternative_name: null,
    alternative_maps_url: null,
    directions_url: 'https://maps.google.com/?q=Secunderabad+Railway+Station',
  },
]

export const SEED_RESTAURANTS = [
  { id: 'rest-1', name: 'Nimrah Cafe & Bakery', meal_type: 'Evening snack', day: 1, time: '5:00 PM', address: 'Near Charminar, Old City', distance: '6 km from station', has_cash_only_note: true, sort_order: 1 },
  { id: 'rest-2', name: 'Cafe Shadab', meal_type: 'Dinner', day: 1, time: '7:00 PM', address: '5 min walk from Charminar', distance: '5 min walk', has_cash_only_note: false, sort_order: 2 },
  { id: 'rest-3', name: 'Eat Street', meal_type: 'Late night', day: 1, time: '10:00 PM', address: 'Necklace Road', distance: '2 min walk', has_cash_only_note: false, sort_order: 3 },
  { id: 'rest-4', name: 'Bawarchi', meal_type: 'Lunch', day: 2, time: '12:00 PM', address: 'RTC Cross Road, Chikkadapally', distance: '5 km from Chowmahalla', has_cash_only_note: false, sort_order: 4 },
  { id: 'rest-5', name: 'Chutneys', meal_type: 'Snack', day: 2, time: '4:00 PM', address: 'Banjara Hills', distance: '3 km from KBR', has_cash_only_note: false, sort_order: 5 },
  { id: 'rest-6', name: 'Paradise Biryani', meal_type: 'Dinner', day: 2, time: '5:30 PM', address: 'Sarojini Devi Road, Secunderabad', distance: '8 km from Banjara Hills', has_cash_only_note: false, sort_order: 6 },
]

export const SEED_MENU_ITEMS = [
  { restaurant_id: 'rest-1', name: 'Irani Chai', price: 25, diet: 'veg', sort_order: 1 },
  { restaurant_id: 'rest-1', name: 'Osmania Biscuits', price: 30, diet: 'veg', sort_order: 2 },
  { restaurant_id: 'rest-1', name: 'Bun Maska', price: 50, diet: 'veg', sort_order: 3 },
  { restaurant_id: 'rest-2', name: 'Mutton Biryani', price: 220, diet: 'non-veg', sort_order: 1 },
  { restaurant_id: 'rest-2', name: 'Seekh Kebabs', price: 180, diet: 'non-veg', sort_order: 2 },
  { restaurant_id: 'rest-2', name: 'Haleem', price: 150, diet: 'non-veg', sort_order: 3 },
  { restaurant_id: 'rest-2', name: 'Veg Biryani', price: 150, diet: 'veg', sort_order: 4 },
  { restaurant_id: 'rest-2', name: 'Paneer Butter Masala', price: 160, diet: 'veg', sort_order: 5 },
  { restaurant_id: 'rest-2', name: 'Sheermal', price: 40, diet: 'veg', sort_order: 6 },
  { restaurant_id: 'rest-2', name: 'Qubani Ka Meetha', price: 80, diet: 'veg', sort_order: 7 },
  { restaurant_id: 'rest-2', name: 'Double Ka Meetha', price: 70, diet: 'veg', sort_order: 8 },
  { restaurant_id: 'rest-3', name: 'Shawarma', price: 120, diet: 'non-veg', sort_order: 1 },
  { restaurant_id: 'rest-3', name: 'Sweet Corn Manchurian', price: 80, diet: 'veg', sort_order: 2 },
  { restaurant_id: 'rest-3', name: 'Ice Cream Rolls', price: 100, diet: 'veg', sort_order: 3 },
  { restaurant_id: 'rest-3', name: 'Paneer Tikka', price: 140, diet: 'veg', sort_order: 4 },
  { restaurant_id: 'rest-3', name: 'Kulfi', price: 60, diet: 'veg', sort_order: 5 },
  { restaurant_id: 'rest-4', name: 'Chicken Biryani', price: 260, diet: 'non-veg', sort_order: 1 },
  { restaurant_id: 'rest-4', name: 'Mutton Biryani', price: 320, diet: 'non-veg', sort_order: 2 },
  { restaurant_id: 'rest-4', name: 'Chicken 65', price: 220, diet: 'non-veg', sort_order: 3 },
  { restaurant_id: 'rest-4', name: 'Veg Biryani', price: 200, diet: 'veg', sort_order: 4 },
  { restaurant_id: 'rest-4', name: 'Dal Makhani', price: 160, diet: 'veg', sort_order: 5 },
  { restaurant_id: 'rest-4', name: 'Butter Naan', price: 40, diet: 'veg', sort_order: 6 },
  { restaurant_id: 'rest-4', name: 'Lassi', price: 60, diet: 'veg', sort_order: 7 },
  { restaurant_id: 'rest-5', name: 'Gongura Chicken', price: 280, diet: 'non-veg', sort_order: 1 },
  { restaurant_id: 'rest-5', name: 'Pesarattu', price: 120, diet: 'veg', sort_order: 2 },
  { restaurant_id: 'rest-5', name: 'Masala Dosa', price: 110, diet: 'veg', sort_order: 3 },
  { restaurant_id: 'rest-5', name: 'Idli Sambar', price: 80, diet: 'veg', sort_order: 4 },
  { restaurant_id: 'rest-5', name: 'Filter Coffee', price: 50, diet: 'veg', sort_order: 5 },
  { restaurant_id: 'rest-6', name: 'Chicken Supreme Biryani', price: 300, diet: 'non-veg', sort_order: 1 },
  { restaurant_id: 'rest-6', name: 'Mutton Biryani', price: 360, diet: 'non-veg', sort_order: 2 },
  { restaurant_id: 'rest-6', name: 'Nihari', price: 200, diet: 'non-veg', sort_order: 3 },
  { restaurant_id: 'rest-6', name: 'Veg Dum Biryani', price: 220, diet: 'veg', sort_order: 4 },
  { restaurant_id: 'rest-6', name: 'Paneer Masala', price: 180, diet: 'veg', sort_order: 5 },
  { restaurant_id: 'rest-6', name: 'Lassi Faluda', price: 80, diet: 'veg', sort_order: 6 },
]

export const SEED_CHECKLIST = [
  { id: 'cl-1', category: 'Clothes', label: 'Light cotton clothes (2 days)', sort_order: 1 },
  { id: 'cl-2', category: 'Clothes', label: 'Extra footwear', sort_order: 2 },
  { id: 'cl-3', category: 'Clothes', label: 'Sunglasses', sort_order: 3 },
  { id: 'cl-4', category: 'Essentials', label: 'Sunscreen SPF 50+', sort_order: 4 },
  { id: 'cl-5', category: 'Essentials', label: 'Refillable water bottle', sort_order: 5 },
  { id: 'cl-6', category: 'Essentials', label: 'Power bank', sort_order: 6 },
  { id: 'cl-7', category: 'Essentials', label: 'Earphones', sort_order: 7 },
  { id: 'cl-8', category: 'Essentials', label: 'ID proof', sort_order: 8 },
  { id: 'cl-9', category: 'Essentials', label: 'Cash (min Rs. 2,000)', sort_order: 9 },
  { id: 'cl-10', category: 'Essentials', label: 'UPI apps ready', sort_order: 10 },
  { id: 'cl-11', category: 'Health', label: 'ORS packets', sort_order: 11 },
  { id: 'cl-12', category: 'Health', label: 'Paracetamol', sort_order: 12 },
  { id: 'cl-13', category: 'Health', label: 'Antacid', sort_order: 13 },
  { id: 'cl-14', category: 'Health', label: 'Hand sanitiser', sort_order: 14 },
  { id: 'cl-15', category: 'Travel', label: 'Train ticket downloaded', sort_order: 15 },
  { id: 'cl-16', category: 'Travel', label: 'Hotel booking confirmed', sort_order: 16 },
  { id: 'cl-17', category: 'Travel', label: 'Hyderabad offline map downloaded', sort_order: 17 },
  { id: 'cl-18', category: 'Travel', label: 'Uber app installed', sort_order: 18 },
]

export const SEED_TIPS = [
  { content: 'UPI works everywhere in Old City, even at bangle stalls in Laad Bazaar.', sort_order: 1 },
  { content: 'Always book Uber or Ola via app. Never negotiate with auto drivers near tourist spots — they will overcharge.', sort_order: 2 },
  { content: 'Cover shoulders at Charminar and Mecca Masjid. It is a place of worship.', sort_order: 3 },
  { content: 'Carry Rs. 100 and Rs. 50 notes. Old City vendors struggle with large bills.', sort_order: 4 },
  { content: 'June heat peaks between 11 AM and 4 PM. Carry a refillable water bottle and ORS packets.', sort_order: 5 },
  { content: 'At Laad Bazaar, start bargaining at 40% of the quoted price. Work up from there.', sort_order: 6 },
  { content: 'Nimrah Cafe is cash only. No UPI, no card. Non-negotiable.', sort_order: 7 },
  { content: 'Chowmahalla Palace is closed on Fridays. June 19 is Thursday — it is open.', sort_order: 8 },
  { content: 'Paradise Biryani (Secunderabad branch) is 2 min from Secunderabad station — perfect for the last meal.', sort_order: 9 },
]

export const SEED_CONTACTS = [
  { label: 'Police', number: '100', sort_order: 1 },
  { label: 'Ambulance', number: '108', sort_order: 2 },
  { label: 'Hyderabad helpline', number: '040-27852425', sort_order: 3 },
  { label: 'Osmania General Hospital', number: '040-24600177', sort_order: 4 },
]

export async function seedIfEmpty() {
  try {
    const { data } = await supabase.from('stops').select('*')

    if (!data || data.length === 0) {
      await supabase.from('stops').upsert(SEED_STOPS).then()
      await supabase.from('restaurants').upsert(SEED_RESTAURANTS).then()
      await supabase.from('menu_items').insert(SEED_MENU_ITEMS).then()
      await supabase.from('checklist_definitions').upsert(SEED_CHECKLIST).then()
      await supabase.from('trip_tips').insert(SEED_TIPS).then()
      await supabase.from('emergency_contacts').insert(SEED_CONTACTS).then()
      await supabase.from('app_settings').upsert(SEED_SETTINGS).then()
    }
  } catch (err) {
    console.error('Seed failed:', err)
  }
}
